project:
  type: book
  output-dir: docs

lang: fr
execute: 
  echo: fenced
book:
  title: "Loto"
  downloads: pdf
  page-footer: "Merci à [Git](https://git-scm.com/), [github](https://github.com/), [Python](https://www.python.org/), [quarto](https://quarto.org/), [RStudio](https://posit.co/download/rstudio-desktop/), [R](https://cran.rstudio.com/) et [Wikipédia](https://fr.wikipedia.org/wiki/Wikip%C3%A9dia:Accueil_principal)"
  author:
    - name: Roger MARTIN
      email: Roger57que@free.fr
  date-format: "ddd DD MMM YYYY"
  date: 2024-03-12

  chapters:
    - index.qmd
  appendices: 
    - references.qmd
    
  sidebar: 
    style: floating
    tools: 
      - icon: github
        menu: 
          - text: Code source
            url: https://github.com/CzernaiFR/Loto
          - text: Site
            url: https://czernaifr.github.io/Loto/

bibliography: references.bib
reference-location: margin
footnotes-hover: true
citation-location: margin
format:
  html:
    theme:
      dark: darkly
      light: lux
    highlight-style: vim-dark
    fontsize: 1.35em
    grid: 
      sidebar-width: 225px
      margin-width: 300px
      gutter-width: 0.5rem
  pdf:
    documentclass: scrreprt



